name: "⚠️ Report an Issue"
description: "Please let us know if something is not right..."
labels: ["bug"]
assignees:
  - smashedr

body:
  - type: markdown
    attributes:
      value: |
        ### All issues will be responded too.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: Please describe the issue you are experiencing and how to reproduce.
      placeholder: Provide as many details as you can...

  - type: input
    id: website
    validations:
      required: false
    attributes:
      label: Site Link
      description: Please provide a link to

  - type: textarea
    id: support
    validations:
      required: true
    attributes:
      label: Support Information
      description: Open the extension options, scroll to the bottom, click Copy Support Information and paste below.
      render: shell

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to make this report!
