name: "💡 Request a Feature"
description: "Request New Features or Enhancements"
labels: ["enhancement"]
assignees:
  - smashedr

body:
  - type: markdown
    attributes:
      value: |
        All issues will be responded too.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Details
      description: Please describe the feature or enhancement you are requesting and what it should do.
      placeholder: Provide as many details as you can...

  #- type: textarea
  #  id: logs
  #  validations:
  #    required: false
  #  attributes:
  #    label: Log Output
  #    description: Text in this box is automatically wrapped in a code block.
  #    render: shell

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to make this report!
