name: "🛠️ Request Server Support"
description: "Request support for a ShareX server"
labels: ["server"]
assignees:
  - smashedr

body:
  - type: markdown
    attributes:
      value: |
        The name of the server software or similar.

  - type: input
    id: url
    validations:
      required: false
    attributes:
      label: Server Software Link
      description: Please provide a link to the server software you are using (not your hosted server).
      placeholder: https://django-files.github.io/

  - type: textarea
    id: description
    validations:
      required: false
    attributes:
      label: Description
      description: Additional details of the server you are requesting.
      placeholder: The body of the request, add any relevant information here.

  - type: textarea
    id: config
    validations:
      required: false
    attributes:
      label: ShareX Custom Uploader (*.sxcu) Configuration
      description: Output is automatically wrapped in a code block.
      render: shell
      placeholder: |
        {
          "Version": "15.0.0",
          "RequestMethod": "POST",
          "RequestURL": "REDACTED",
          "Headers": { "Authorization": "REDACTED" },
          "Body": "MultipartFormData",
          "URL": "{json:url}",
          ...
        }

  - type: markdown
    attributes:
      value: |
        Make sure to **remove any personally identifiable information** before submitting!

        Thank you for taking the time to make this report!
