name: "🛠️ Request Server Support"
description: "Request support for a ShareX server"
labels: ["server"]
assignees:
  - smashedr

body:
  - type: markdown
    attributes:
      value: |
        All issues will be responded too.

  - type: input
    id: url
    validations:
      required: false
    attributes:
      label: Server Software Link
      description: Please provide a link to the server software you are using (not your server).
      placeholder: https://django-files.github.io/

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Details
      description: Please describe the feature or enhancement you are requesting and what it should do.
      placeholder: Provide as many details as you can...

  - type: textarea
    id: config
    validations:
      required: true
    attributes:
      label: ShareX Custom Uploader `*.sxcu` configuration
      description: IMPORTANT! Make sure to REDACT your Authorization/Token!
      render: shell

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to make this report!
